# Generated by Django 4.1.3 on 2022-11-19 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('fornecedor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fornecedor_cnpj', models.CharField(max_length=18)),
                ('fornecedor_nome', models.CharField(max_length=50)),
                ('fornecedor_cadastro_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fornecedores',
                'managed': True,
            },
        ),
    ]
