# Generated by Django 4.1.3 on 2022-11-19 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('vereador_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vereador_matricula', models.CharField(max_length=15)),
                ('Vereador_nome', models.CharField(max_length=50)),
                ('vereador_cadastro_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vereadores',
                'managed': True,
            },
        ),
    ]
