# Generated by Django 4.1.3 on 2022-11-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0002_alter_vereador_vereador_cadastro_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vereador',
            old_name='Vereador_nome',
            new_name='vereador_nome',
        ),
    ]
