# Generated by Django 4.1.3 on 2022-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_materiais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_descricao', models.CharField(max_length=50)),
                ('material_valor', models.CharField(max_length=50)),
                ('material_quantidade', models.IntegerField()),
                ('material_data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_material', to='material.tipomaterial')),
            ],
            options={
                'db_table': 'materiais',
                'managed': True,
            },
        ),
    ]
