# Generated by Django 4.1.3 on 2022-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
