# Generated by Django 4.1.3 on 2022-12-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_material_material_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='tipo_material',
        ),
        migrations.AddField(
            model_name='material',
            name='material_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_tipo', to='material.tipomaterial'),
        ),
    ]
