# Generated by Django 4.1.3 on 2022-12-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_alter_fornecedor_fornecedor_cadastro_data'),
        ('material', '0004_remove_material_tipo_material_material_material_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_detalhe', to='fornecedor.fornecedor'),
        ),
    ]
