# Generated by Django 4.1.3 on 2022-11-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('destino_id', models.AutoField(primary_key=True, serialize=False)),
                ('destino_descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'destinos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilizado',
            fields=[
                ('utilizado_id', models.AutoField(primary_key=True, serialize=False)),
                ('utilizado_quantidade', models.IntegerField()),
                ('destino_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinoDetalhes', to='utilizado.destino')),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialDetalhes', to='material.material')),
            ],
            options={
                'db_table': 'utilizados',
                'managed': True,
            },
        ),
    ]
