# Generated by Django 4.1.3 on 2022-11-20 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizado',
            name='utilizado_data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 20, 23, 45, 43, 398348, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
