# Generated by Django 4.1.3 on 2022-12-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizado', '0002_utilizado_utilizado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizado',
            name='destino_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
