# Generated by Django 4.1.3 on 2022-12-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vereador', '0003_rename_vereador_nome_vereador_vereador_nome'),
        ('utilizado', '0004_alter_utilizado_destino_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizado',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='utilizado',
            name='destino_id',
        ),
        migrations.AddField(
            model_name='utilizado',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinoDetalhes', to='utilizado.destino'),
        ),
        migrations.AddField(
            model_name='utilizado',
            name='utilizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vereadorDetalhes', to='vereador.vereador'),
        ),
    ]
