# Generated by Django 4.1.3 on 2022-12-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizado', '0005_rename_material_id_utilizado_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizado',
            old_name='destino',
            new_name='destino_id',
        ),
        migrations.RenameField(
            model_name='utilizado',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='utilizado',
            old_name='utilizador',
            new_name='utilizador_id',
        ),
    ]
