# Generated by Django 4.1.3 on 2022-12-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizado', '0006_rename_destino_utilizado_destino_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizado',
            old_name='destino_id',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='utilizado',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='utilizado',
            old_name='utilizador_id',
            new_name='utilizador',
        ),
    ]
